version: '3'

services:
  jenkins:
    container_name: 'Jenkins'
    image: 'jenkins/jenkins:lts'
    restart: always
    volumes:
      - './html:/usr/share/jenkins/html'
      - './jenkins/data:/var/jenkins_home'

  gitlab:
    container_name: 'GitLab'
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    ports:
      - '22:22'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
       external_url 'http://gitlab.fe.com'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'

  nginx:
    container_name: 'Nginx'
    depends_on:
      - jenkins
      - gitlab
    image: nginx:alpine
    volumes:
      - './html:/usr/share/nginx/html'
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './nginx/vhost:/etc/nginx/vhost'
    ports:
      - 80:80
    restart: always

  dns:
    container_name: 'DNS'
    image: 'jpillora/dnsmasq'
    ports:
      # - 8080:8080
      - 53:53/udp
    restart: always
    volumes:
      - './dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf'
