version: '3'

services:
  nginx:
    container_name: nginx
    image: 'nginx:alpine'
    volumes:
      - './html:/usr/share/nginx/html'
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './nginx/vhost:/etc/nginx/vhost'
    ports:
      - 80:80
    restart: always
    depends_on:
      - kibana
      - node

  elasticsearch:
    container_name: elasticsearch
    image: 'elasticsearch:6.5.4'
    restart: always

  node:
    container_name: node
    build: ./node
    restart: always
    depends_on:
      - fluentd

  fluentd:
    container_name: fluentd
    build: ./fluentd
    volumes:
      - ./fluentd:/fluentd/etc/
    restart: always
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    image: kibana:6.5.4
    restart: always
    depends_on:
      - fluentd
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200