version: '3'

services:
  # jenkins:
  #   container_name: 'Jenkins'
  #   image: 'jenkins/jenkins:lts'
  #   restart: always
  #   volumes:
  #     - './html:/usr/share/jenkins/html'
  #     - './jenkins/data:/var/jenkins_home'

  # gitlab:
  #   container_name: 'GitLab'
  #   image: 'gitlab/gitlab-ce:latest'
  #   restart: always
  #   ports:
  #     - '22:22'
  #   volumes:
  #     - './gitlab/config:/etc/gitlab'
  #     - './gitlab/logs:/var/log/gitlab'
  #     - './gitlab/data:/var/opt/gitlab'

  # nginx:
  #   container_name: 'Nginx'
  #   image: nginx:alpine
  #   volumes:
  #     - './html:/usr/share/nginx/html'
  #     - './nginx/nginx.conf:/etc/nginx/nginx.conf'
  #     - './nginx/vhost:/etc/nginx/vhost'
  #   ports:
  #     - 80:80
  #   restart: always
  #   depends_on:
  #     - jenkins
  #     - gitlab
  #     - node1
  #     - node2
  #     - node3
  #     - node4
  #     - node5

  node1:
    container_name: 'Node-1'
    build: './node'
    tty: true
    volumes:
      - './ssh/authorized_keys:/root/.ssh/authorized_keys'
    environment:
      - ENV_LABEL=node1
    ports:
      - 221:22

  node2:
    container_name: 'Node-2'
    build: './node'
    tty: true
    volumes:
      - './ssh/authorized_keys:/root/.ssh/authorized_keys'
    environment:
      - ENV_LABEL=node2
    ports:
      - 222:22