version: '3'

services:
  jenkins:
    container_name: 'Jenkins'
    image: 'jenkins/jenkins:lts'
    restart: always
    volumes:
      - './jenkins/data:/var/jenkins_home'

  gitlab:
    container_name: 'GitLab'
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
       external_url 'http://gitlab.fe.com'
    ports:
      - '22:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'

  nginx:
    container_name: 'Nginx'
    image: nginx:alpine
    volumes:
      - './html:/usr/share/nginx/html'
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './nginx/vhost:/etc/nginx/vhost'
    ports:
      - 80:80
    restart: always
    depends_on:
      - jenkins
      - gitlab
      - node1
      - node2
      - node3
      - node4
      - node5

  node1:
    container_name: 'Node-1'
    build: './node'
    tty: true
    env_file: .env
    environment:
      - ENV_LABEL=node1
      - AUTHORIZED_KEYS=${AUTHORIZED_KEYS}
    ports:
      - '2221:22'

  node2:
    container_name: 'Node-2'
    build: './node'
    tty: true
    env_file: .env
    environment:
      - ENV_LABEL=node2
      - AUTHORIZED_KEYS=${AUTHORIZED_KEYS}
    ports:
      - '2222:22'

  node3:
    container_name: 'Node-3'
    build: './node'
    tty: true
    env_file: .env
    environment:
      - ENV_LABEL=node3
      - AUTHORIZED_KEYS=${AUTHORIZED_KEYS}
    ports:
      - '2223:22'

  node4:
    container_name: 'Node-4'
    build: './node'
    tty: true
    env_file: .env
    environment:
      - ENV_LABEL=node4
      - AUTHORIZED_KEYS=${AUTHORIZED_KEYS}
    ports:
      - '2224:22'

  node5:
    container_name: 'Node-5'
    build: './node'
    tty: true
    env_file: .env
    environment:
      - ENV_LABEL=node5
      - AUTHORIZED_KEYS=${AUTHORIZED_KEYS}
    ports:
      - '2225:22'