version: '3'

services:
  jenkins:
    container_name: jenkins
    image: 'jenkins/jenkins:lts'
    restart: always
    volumes:
      - './jenkins/data:/var/jenkins_home'

  gitlab:
    container_name: gitlab
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
       external_url 'http://gitlab.fe.com'
    ports:
      - '22:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'

  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - './html:/usr/share/nginx/html'
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './nginx/vhost:/etc/nginx/vhost'
    ports:
      - 80:80
    restart: always
    depends_on:
      - jenkins
      - gitlab
      - node1
      - node2
      - node3
      - node4
      - node5

  node1:
    container_name: node1
    build: './node'
    tty: true
    env_file: .env
    environment:
      - ENV_LABEL=node1
      - AUTHORIZED_KEYS=${AUTHORIZED_KEYS}

  node2:
    container_name: node2
    build: './node'
    tty: true
    env_file: .env
    environment:
      - ENV_LABEL=node2
      - AUTHORIZED_KEYS=${AUTHORIZED_KEYS}

  node3:
    container_name: node3
    build: './node'
    tty: true
    env_file: .env
    environment:
      - ENV_LABEL=node3
      - AUTHORIZED_KEYS=${AUTHORIZED_KEYS}

  node4:
    container_name: node4
    build: './node'
    tty: true
    env_file: .env
    environment:
      - ENV_LABEL=node4
      - AUTHORIZED_KEYS=${AUTHORIZED_KEYS}

  node5:
    container_name: node5
    build: './node'
    tty: true
    env_file: .env
    environment:
      - ENV_LABEL=node5
      - AUTHORIZED_KEYS=${AUTHORIZED_KEYS}